apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: source-transformer-bypass
spec:
  bypass:
    sink:
      tags:
        operator: or
        values:
          - sink
    fallback:
      tags:
        operator: or
        values:
          - fallback
    onSuccess:
      tags:
        operator: or
        values:
          - onSuccess
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 10
          duration: 1s
          keyCount: 5
          value: 5
        transformer:
          container:
            image: quay.io/numaio/numaflow-rs/source-transformer-now:stable
            imagePullPolicy: Always
    - name: output
      sink:
        udsink:
          container:
            # A redis sink for e2e testing, see https://github.com/numaproj/numaflow-go/tree/main/examples/sinker/redis_sink
            image: quay.io/numaio/numaflow-go/redis-sink:stable
            imagePullPolicy: IfNotPresent
            env:
              - name: SINK_HASH_KEY
                # The key is set in the format of "pipeline_name-vertex_name"
                value: "simple-output"
        fallback:
          udsink:
            container:
              # A redis sink for e2e testing, see https://github.com/numaproj/numaflow-go/tree/main/examples/sinker/redis_sink
              image: quay.io/numaio/numaflow-go/redis-sink:stable
              imagePullPolicy: IfNotPresent
              env:
                - name: SINK_HASH_KEY
                  # The key is set in the format of "pipeline_name-vertex_name"
                  value: "simple-fallback-output"
        onSuccess:
          udsink:
            container:
              # A redis sink for e2e testing, see https://github.com/numaproj/numaflow-go/tree/main/examples/sinker/redis_sink
              image: quay.io/numaio/numaflow-go/redis-sink:stable
              imagePullPolicy: IfNotPresent
              env:
                - name: SINK_HASH_KEY
                  # The key is set in the format of "pipeline_name-vertex_name"
                  value: "simple-on-success-output"
  edges:
    - from: in
      to: output