apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-sideinput
spec:
  sideInputs:
    - name: myticker
      container:
        image: quay.io/numaio/numaflow-rs/sideinput-example:stable
        imagePullPolicy: IfNotPresent
      trigger:
        schedule: "0 */2 * * * *"
        #timezone: America/Los_Angeles
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 1
          duration: 1s
    - name: si-log
      udf:
        container:
          image: quay.io/numaio/numaflow-rs/udf-sideinput-example:stable
          imagePullPolicy: Always
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
      sideInputs:
        - myticker
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: si-log
    - from: si-log
      to: out