apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: rust-batchmap-batchmap
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 500
          duration: 1s
          keyCount: 5
          value: "hello,hello"
    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-rs/batchmap-flatmap:stable
    - name: out
      sink:
        # A simple log printing sink
        log: { }
  edges:
    - from: in
      to: cat
    - from: cat
      to: out


