[package]
name = "all-sinks"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
rand = "0.9.2"
tonic.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
numaflow = { path = "../../numaflow" }
