[package]
name = "redis-sink"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tonic.workspace = true
tokio.workspace = true
numaflow = { path = "../../numaflow" }
redis = { version = "1.0.0", features = ["tokio-comp", "aio"] }