apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-reduce-stream
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 10
          duration: 1s
          keyCount: 5
          value: 5
    - name: streaming-counter
      udf:
        container:
          # count element with streaming results
          image: quay.io/numaio/numaflow-rs/reduce-stream-counter:stable
        groupBy:
          window:
            fixed:
              length: 10s
              streaming: true
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 10Gi
              accessMode: ReadWriteOnce
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: streaming-counter
    - from: streaming-counter
      to: out

