apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-rust-map-cat
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 300
          duration: 1s
          keyCount: 5
          value: 5
    - name: cat
      scale:
        min: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-rs/map-cat:stable
    - name: out
      sink:
        # A simple log printing sink
        log: { }
  edges:
    - from: in
      to: cat
    - from: cat
      to: out


